site_name: xDrip+

theme:
    name: material
    language: en
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
    logo: xDrip+logo.png
    favicon: xDrip+logo.png
    palette:
      primary: white
      scheme: default
    nav_style: primary

extra_css:
    - css/admonitions.css

markdown_extensions:
    - admonition
    - tables
    - toc:
        permalink: ‚åÅ
        
nav:
    - Getting started:
        - 'How to use this documentation?': 'install/usethedoc.md'
        - 'Prerequisites': 'install/prerequisites.md'
        - 'Download': 'install/download.md'
        - 'Installation': 'install/install.md'
        - 'Data source': 'install/datasource.md'
        - 'G4': 'install/g4.md'
        - 'G5': 'install/g5.md'
        - 'G6': 'install/g6.md'
        - 'Libre NFC': 'install/libreNFC.md'
        - 'LibreAlarm': 'install/librealarm.md'
        - 'Libre bridge': 'install/libreBT.md'
        - 'Libre 2 Direct': 'install/libre2.md'
        - 'Libre 2 Direct QR Settings': 'install/libre2direct-qr-settings.md'
        - 'Libre 2 patch': 'install/libre2patch.md'
        - 'Eversense': 'install/eversense.md'
        - 'Medtrum': 'install/medtrum.md'
        - '640G/670G': 'install/640_670.md'
        - 'xDrip+ follower': 'install/xdripfollower.md'
        - 'Nightscout follower': 'install/nightscoutfollower.md'
        - 'Dex Share follower': 'install/dexshare.md'
        - 'CareLink follower': 'install/carelinkfollow.md'
        - 'BYODA': 'install/byod.md'
        - 'Companion app': 'install/companion.md'
        - 'GlucoRx/Aidex': 'install/aidex.md'
        - 'Web Follower': 'install/webfollower.md'
    - Discover and use:
        - 'Main view': 'use/mainUI.md'
        - 'Main menu': 'use/hamburger.md'
        - 'Start sensor': 'use/startsensor.md'
        - 'Stop sensor': 'use/stopsensor.md'
        - 'Statistics': 'use/statistics.md'
        - 'Alarms and Alerts': 'use/alarms.md'
        - 'Speak Readings': 'use/speak.md'
        - 'Glucose Meter': 'use/glucometer.md'
        - 'Sync Follower setup': 'use/syncsetup.md'
    - Calibrations:
        - 'Calibration basics': 'calibrate/101.md'
        - 'Calibrate': 'calibrate/calibrate.md'
        - 'Troubleshooting': 'calibrate/troubleshoot.md'
    - Settings:
        - 'Settings': 'use/settings.md'
        - 'Display': 'use/display.md'
        - '3 Dots menu': 'use/3dotsmenu.md'
        - 'Copy settings': 'use/copysettings.md'
        - 'Load / Save Settings': 'use/loadsavesettings.md'
        - 'xDrip+ Sync': 'use/sync.md'
        - 'Cloud Upload': 'use/cloud.md'
        - 'Predictive Simulation': 'use/predictions.md'
        - 'Motion Tracking': 'use/motion.md'
        - 'Update': 'use/update.md'
        - 'Inter-apps': 'use/interapp.md'
        - 'Less Common Settings': 'use/lesscommon.md'
        - 'Advanced Calibration': 'calibrate/advancedcal.md'
        - 'Bluetooth Settings': 'use/bluetooth.md'
        - 'Other Misc. Options': 'use/misc.md'
        - 'Out of Process Algorithm': 'use/OOP.md'
        - 'Insulin Pens': 'use/pens.md'
        - 'G5/G6 Debug Settings': 'use/g56debug.md'
        - 'Spoken Commands': 'use/spokencommands.md'
    - Smartwatch:
        - 'Smartwatches': 'smartwatch/smartwatch.md'
        - 'Android Wear': 'smartwatch/wear.md'
        - 'Install on Android Wear': 'smartwatch/wearinstall.md'
        - 'Use Wear Extension': 'smartwatch/usewear.md'
        - 'Pebble': 'smartwatch/pebble.md'
        - 'MiBand': 'smartwatch/miband.md'
        - 'BlueJay Watch': 'smartwatch/bluejay.md'
    - Troubleshooting:
        - 'Installation': 'troubleshoot/install.md'
        - 'Reinstallation': 'troubleshoot/reinstall.md'
        - 'System Status': 'troubleshoot/systemstatus.md'
        - 'Libre Bridge': 'troubleshoot/librebridge.md'
        - 'Libre 2': 'troubleshoot/libre2.md'
        - 'Libre 2 Direct': 'troubleshoot/libre2direct.md'
        - 'Bridge Firmware': 'troubleshoot/bridgeFW.md'
        - 'G5/G6 Connection': 'troubleshoot/connection.md'
        - 'Android Debug Bridge': 'troubleshoot/ADB.md'
        - 'Android Settings': 'troubleshoot/savings.md'
    - Change Log: 'changelog.md'